# Generated by Django 4.2.4 on 2023-08-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="created_at",
            new_name="data",
        ),
    ]
